"""Demo records that simulate data supplied by member C and the presentation group."""

from .models import DataRecord


DATA_RECORDS: tuple[DataRecord, ...] = (
    DataRecord(
        record_id="A001",
        category="attraction",
        content="Grand Palace",
        source_name="Official website",
        url="https://example.test/grand-palace",
        updated_at="2026-05-20",
        is_structured=True,
        city="Bangkok",
        cost_thb=500,
        opens_at="08:30",
        closes_at="15:30",
        tags=("culture", "history", "religion"),
    ),
    DataRecord(
        record_id="A002",
        category="attraction",
        content="Wat Pho",
        source_name="Tourism website",
        url="https://example.test/wat-pho",
        updated_at="2026-05-20",
        is_structured=True,
        city="Bangkok",
        cost_thb=300,
        opens_at="08:00",
        closes_at="18:30",
        tags=("culture", "history", "religion"),
    ),
    DataRecord(
        record_id="A003",
        category="attraction",
        content="Wat Arun",
        source_name="Tourism website",
        url="https://example.test/wat-arun",
        updated_at="2026-05-20",
        is_structured=True,
        city="Bangkok",
        cost_thb=200,
        opens_at="08:00",
        closes_at="18:00",
        tags=("culture", "history", "religion"),
    ),
    DataRecord(
        record_id="A004",
        category="attraction",
        content="Ayutthaya Historical Park",
        source_name="Go2 Thailand",
        url="https://go2-thailand.com/itineraries/5-days-bangkok-central/",
        updated_at="2026-05-22",
        is_structured=True,
        city="Ayutthaya",
        cost_thb=0,
        tags=("culture", "history", "ayutthaya"),
    ),
    DataRecord(
        record_id="A005",
        category="attraction",
        content="Wat Mahathat",
        source_name="Bangkok Driver itinerary reference",
        url="https://bangkokdriver.com/bangkok-5-day-itinerary-a-locals-route/",
        updated_at="2026-05-22",
        is_structured=True,
        city="Ayutthaya",
        cost_thb=200,
        tags=("culture", "history", "ayutthaya"),
    ),
    DataRecord(
        record_id="A006",
        category="attraction",
        content="Wat Ratchaburana",
        source_name="Bangkok Driver itinerary reference",
        url="https://bangkokdriver.com/bangkok-5-day-itinerary-a-locals-route/",
        updated_at="2026-05-22",
        is_structured=True,
        city="Ayutthaya",
        cost_thb=100,
        tags=("culture", "history", "ayutthaya"),
    ),
    DataRecord(
        record_id="A007",
        category="attraction",
        content="Wat Chaiwatthanaram",
        source_name="Bangkok Driver itinerary reference",
        url="https://bangkokdriver.com/bangkok-5-day-itinerary-a-locals-route/",
        updated_at="2026-05-22",
        is_structured=True,
        city="Ayutthaya",
        cost_thb=0,
        tags=("culture", "history", "ayutthaya", "photo"),
    ),
    DataRecord(
        record_id="A008",
        category="attraction",
        content="Bangkok Art and Culture Centre",
        source_name="Official website",
        url="https://www.bacc.or.th/en/contact",
        updated_at="2026-05-22",
        is_structured=True,
        city="Bangkok",
        cost_thb=0,
        opens_at="10:00",
        closes_at="20:00",
        tags=("artsy", "culture", "museum"),
    ),
    DataRecord(
        record_id="A009",
        category="attraction",
        content="Jim Thompson House",
        source_name="MyTripBlueprint itinerary reference",
        url="https://mytripblueprint.com/en/itineraries/bangkok-5-days",
        updated_at="2026-05-22",
        is_structured=True,
        city="Bangkok",
        cost_thb=200,
        tags=("culture", "museum", "history"),
    ),
    DataRecord(
        record_id="B001",
        category="food",
        content="Old Town local lunch",
        source_name="Google Maps",
        url="https://example.test/local-lunch",
        updated_at="2026-05-20",
        is_structured=True,
        city="Bangkok",
        cost_thb=250,
        tags=("food", "local"),
    ),
    DataRecord(
        record_id="B002",
        category="food",
        content="Ari design cafe",
        source_name="Blog",
        url="https://example.test/ari-cafe",
        updated_at="2026-05-20",
        is_structured=True,
        city="Bangkok",
        cost_thb=450,
        tags=("cafe", "instagram", "artsy"),
    ),
    DataRecord(
        record_id="B003",
        category="food",
        content="Thonglor photo cafe",
        source_name="Blog",
        url="https://example.test/thonglor-cafe",
        updated_at="2026-05-20",
        is_structured=True,
        city="Bangkok",
        cost_thb=480,
        tags=("cafe", "instagram", "artsy"),
    ),
    DataRecord(
        record_id="B004",
        category="food",
        content="Riverside cafe",
        source_name="Blog",
        url="https://example.test/riverside-cafe",
        updated_at="2026-05-20",
        is_structured=True,
        city="Bangkok",
        cost_thb=420,
        tags=("cafe", "instagram", "artsy"),
    ),
    DataRecord(
        record_id="D001",
        category="cost",
        content="Premium rooftop bar minimum spend",
        source_name="Venue website",
        url="https://example.test/rooftop-bar",
        updated_at="2026-05-20",
        is_structured=True,
        city="Bangkok",
        cost_thb=6200,
        tags=("nightlife", "premium"),
    ),
    DataRecord(
        record_id="D004",
        category="transport",
        content="Bangkok to Ayutthaya day trip transport",
        source_name="Bangkok Driver itinerary reference",
        url="https://bangkokdriver.com/bangkok-5-day-itinerary-a-locals-route/",
        updated_at="2026-05-22",
        is_structured=True,
        city="Ayutthaya",
        cost_thb=2400,
        tags=("transport", "ayutthaya"),
    ),
    DataRecord(
        record_id="D005",
        category="food",
        content="Five-day meal allowance",
        source_name="Internal estimate from 5D4N draft",
        url="docs/泰國5天4夜行程草案.md",
        updated_at="2026-05-22",
        is_structured=True,
        city="Bangkok",
        cost_thb=3000,
        tags=("food", "estimate"),
    ),
    DataRecord(
        record_id="D006",
        category="transport",
        content="Bangkok city transport allowance",
        source_name="Internal estimate from 5D4N draft",
        url="docs/泰國5天4夜行程草案.md",
        updated_at="2026-05-22",
        is_structured=True,
        city="Bangkok",
        cost_thb=1000,
        tags=("transport", "estimate"),
    ),
    DataRecord(
        record_id="H005",
        category="market",
        content="Local railway night market",
        source_name="Google Maps",
        url="https://example.test/railway-night-market",
        updated_at="2026-05-20",
        is_structured=True,
        city="Bangkok",
        cost_thb=300,
        tags=("nightlife", "market", "budget"),
    ),
    DataRecord(
        record_id="H006",
        category="market",
        content="Jodd Fairs night market",
        source_name="Google Maps",
        url="https://example.test/jodd-fairs",
        updated_at="2026-05-20",
        is_structured=True,
        city="Bangkok",
        cost_thb=450,
        tags=("nightlife", "market"),
    ),
    DataRecord(
        record_id="H001",
        category="market",
        content="Pak Khlong Talat Flower Market",
        source_name="Tourist Bangkok",
        url="https://touristbangkok.com/flower-market-pak-khlong-talad/",
        updated_at="2026-05-22",
        is_structured=True,
        city="Bangkok",
        cost_thb=0,
        tags=("market", "flower", "local"),
    ),
    DataRecord(
        record_id="H002",
        category="market",
        content="ICONSIAM",
        source_name="Love Thailand",
        url="https://www.lovethailand.org/travel/en/17-Bangkok/15591-Iconsiam.html",
        updated_at="2026-05-22",
        is_structured=True,
        city="Bangkok",
        cost_thb=0,
        opens_at="10:00",
        closes_at="22:00",
        tags=("market", "shopping", "riverside"),
    ),
    DataRecord(
        record_id="PENDING-13-001",
        category="activity",
        content="Thai costume photo experience",
        source_name="Activity platform",
        url="https://example.test/thai-costume",
        updated_at="2026-05-20",
        is_structured=True,
        city="Bangkok",
        cost_thb=1200,
        tags=("activity", "culture", "instagram", "artsy"),
    ),
    DataRecord(
        record_id="PENDING-13-002",
        category="activity",
        content="Muay Thai evening show",
        source_name="Activity platform",
        url="https://example.test/muay-thai",
        updated_at="2026-05-20",
        is_structured=True,
        city="Bangkok",
        cost_thb=1500,
        tags=("activity", "nightlife"),
    ),
    DataRecord(
        record_id="PENDING-13-003",
        category="activity",
        content="Rooftop bar or night view activity",
        source_name="Internal estimate from 5D4N draft",
        url="docs/泰國5天4夜行程草案.md",
        updated_at="2026-05-22",
        is_structured=True,
        city="Bangkok",
        cost_thb=2000,
        tags=("activity", "nightlife", "premium"),
    ),
    DataRecord(
        record_id="A101",
        category="attraction",
        content="Doi Suthep",
        source_name="Tourism website",
        url="https://example.test/doi-suthep",
        updated_at="2026-05-20",
        is_structured=True,
        city="Chiang Mai",
        cost_thb=100,
        tags=("culture", "mountain", "religion"),
    ),
    DataRecord(
        record_id="H101",
        category="market",
        content="Chiang Mai night bazaar",
        source_name="Google Maps",
        url="https://example.test/chiang-mai-night-bazaar",
        updated_at="2026-05-20",
        is_structured=True,
        city="Chiang Mai",
        cost_thb=300,
        tags=("nightlife", "market"),
    ),
)
